version: '3'

# Production environment should be done in ci/cd securely
# in the purpose of the challenge i have this place here

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile.prod
    environment:
      APP_ENV: prod
      APP_SECRET: g9gxgvv9bgy5kdpa
      DATABASE_URL: postgresql://my_user:Cat8D8agK33hJcQK@database:5432/data_importer?serverVersion=13&charset=utf8"
    volumes:
      - .:/var/www/html

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: data_importer
      POSTGRES_PASSWORD: Cat8D8agK33hJcQK
      POSTGRES_USER: my_user
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  server:
    image: nginx:alpine
    volumes:
        - .:/var/www/html
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
        - app
    ports:
        - "8080:80"

volumes:
  db-data:
