version: '3'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile.prod
    environment:
      APP_ENV: test
    volumes:
      - .:/var/www/html

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: data_importer_test
      POSTGRES_PASSWORD: password1234
      POSTGRES_USER: tester
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
