services:
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Tests\Fakes\:
        resource: '../tests/Fakes'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\Importer\Contract\DataProviderFactoryInterface: '@App\Tests\Fakes\Service\Importer\FakeDataProviderFactory'
